export const SEOITEMNAME = "seo item name",
  CANONICAL = "canonical",
  JSONLD = "jsonLd",
  OGTITLE = "ogTitle",
  OGTYPE = "ogType",
  OGURL = "ogUrl",
  OGIMAGE = "ogImage",
  TITLE = "title",
  METADESCRIPTION = "metaDescription",
  SINGLETYPE = "singleType",
  COLLECTIONTYPE = "collectionType",
  USER_ENABLED_LOCALES_DUMMY = [
    {
      code: "en",
      created_at: "2022-02-14T08:99:59.571Z",
      id: 1,
      isDefault: true,
      name: "English (en)",
      updated_at: "2022-02-14T08:33:59.571Z",
    },
  ];
